const constants = {
    GET_TODO_REQUEST: "GET_TODO_REQUEST",
    GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
    GET_TODO_FAILURE: "GET_TODO_FAILURE",
    GET_TASK_REQUEST: "GET_TASK_REQUEST",
    GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
    GET_TASK_FAILURE: "GET_TASK_FAILURE",
    ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
    TOGGLE_TASK_REQUEST: "TOGGLE_TASK_REQUEST",
    TOGGLE_TASK_SUCCESS: "TOGGLE_TASK_SUCCESS",
    TOGGLE_TASK_FAILURE: "TOGGLE_TASK_FAILURE",
    DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE", 
}

export default constants;