const todoConstants = {
    GET_TODOS_REQUEST: "GET_TODOS_REQUEST",
    GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
    GET_TODOS_FAILURE: "GET_TODOS_FAILURE",
    ADD_TODOS_REQUEST: "ADD_TODOS_REQUEST",
    ADD_TODOS_SUCCESS: "ADD_TODOS_SUCCESS",
    ADD_TODOS_FAILURE: "ADD_TODOS_FAILURE",
}

export {
    todoConstants
}

